variables:
  AUTOTESTS_REPO: 'autotests'
  AUTOTESTS_BRANCH: 'dev'

include:
  - project: 'cicd/gitlabci-templates'
    ref: dev
    file:
    - '/vault/vault-template.yml'
    - '/test/autotests-template.yml'

stages:
  - autotests-api
  - autotests-ui

.autotests_common:
  extends:
    - .vault
  script:
    - echo 'Autotests environment -' ${CI_ENVIRONMENT_NAME}
    - echo 'AUTOTESTS_REPO - ' ${AUTOTESTS_REPO}
    - echo 'AUTOTESTS_BRANCH - ' ${AUTOTESTS_BRANCH}
    - git config --global --add safe.directory ${CI_PROJECT_DIR}
    - git config --global user.name "${GITLAB_USER_LOGIN}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git clone --single-branch --branch ${AUTOTESTS_BRANCH}  https://${GITOPS_LOGIN}:${GITOPS_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_ROOT_NAMESPACE}/${AUTOTESTS_REPO}.git || echo "no ${CI_PROJECT_ROOT_NAMESPACE}/${AUTOTESTS_REPO} repo"
    - apk update && apk add gettext
    - envsubst < testrail.cfg > /tmp/testrail.cfg
    - bash autotests.sh ${ARG}
  artifacts:
    paths:
      - autotest_reports/
    when: always
    expire_in: 7 day

autotests-api:
  stage: autotests-api
  image: ${REGISTRY_URL}/docker/testrail/autotests-api/testrail-autotests-api:latest
  variables:
    ARG: api
  extends:
    - .autotests_common
  when: manual

autotests-ui:
  stage: autotests-ui
  image: ${REGISTRY_URL}/docker/testrail/autotests-web/testrail-autotests-web:latest
  variables:
    ARG: ui
  extends:
    - .autotests_common
  when: manual